# Generated by Django 3.1.1 on 2021-03-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210322_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='upvote',
        ),
    ]
